preset: laravel

finder:
  exclude:
    - "node_modules"
    - "storage"
    - "vendor"
  name: "*.php"
  not-name:
    - "*.blade.php"
    - "index.php"
    - "server.php"

disabled:
  - concat_without_spaces
  - not_operator_with_successor_space
